# Generated by Django 4.1.7 on 2023-07-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekho_app', '0002_categories_delete_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
