# Generated by Django 4.1.7 on 2023-08-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekho_app', '0008_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
