# Generated by Django 4.1.7 on 2023-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekho_app', '0011_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.IntegerField(null=True),
        ),
    ]
