# Generated by Django 4.1.7 on 2023-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekho_app', '0015_course_certificate_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
